### PR TITLE
Add start provider configuration

### PR DESCRIPTION
**Pull request by rovast**
Some providers may need configuration to start, so we can input the configuration in UI, and pass the configuration to host_core.

image

### CODE REVIEW

**Comment by autodidaddict** [comment]
This looks great!

**Review by connorsmith256 — DISMISSED** [review]
Great addition! Should we support providing config to providers started from a file as well?

**Review by connorsmith256 — DISMISSED** [review]

**Comment by brooksmtownsend** [comment]
@rovast looks like this might just be missing something that's failing in the tests, probably the change in the number of arguments that go into `start_provider_from_file`

**Comment by rovast** [comment]
> @rovast looks like this might just be missing something that's failing in the tests, probably the change in the number of arguments that go into `start_provider_from_file`

Help wanted. ✋ 

When I was developing this function, I found the same question the argument number does not match, and it confused me for a long while(That's why in the first version PR, [I ignore the support for the file](https://github.com/wasmCloud/wasmcloud-otp/pull/498#pullrequestreview-1184653513)). 

But after I changed the  `start_provider_from_file ` function, and reboot the host, the function works, and the issue is fixed. 

I'm not very familiar with Elixir, could you please edit the code directly? Thanks a lot.

**Comment by brooksmtownsend** [comment]
@rovast sure thing, someone on the maintainer side should be able to tweak the arguments here in a bit and push to this PR. I appreciate you getting this feature so far and we're happy to just double check the Elixir bits 😄

**Comment by connorsmith256** [comment]
@rovast @brooksmtownsend I think this was a case of flaky tests 😞 I noticed different tests failed on the 1st and 2nd run, and I just triggered a 3rd try and everything passed

@brooksmtownsend have we see flaky e2e tests before? The common failure between the two was trying to contact http://localhost:8081

**Comment by brooksmtownsend** [comment]
> @brooksmtownsend have we see flaky e2e tests before? The common failure between the two was trying to contact http://localhost:8081/

Occasionally, yes, but I'm not sure exactly what happened in the previous run. I think we can give this a go locally and a few test runs in CI to make sure it's all good

**Comment by brooksmtownsend** [comment]
@rovast I think the only thing we need here is a rebase, everything looks good!

**Comment by rovast** [comment]
@brooksmtownsend ok, rebase is done, and all checks have passed. 😃

**Comment by stevelr** [comment]
I like this! I have a few questions about implementation details:

Is the data type of provider_configuration a map or a string?

Should it be included when the host reports inventory? (What if the config includes secrets?)

Will it be added to HostData to send to providers on startup? I don't think I noticed a pr to the interface repo for the change to model-core.

**Comment by connorsmith256** [comment]
@stevelr this change isn't adding a new kind of configuration, it's allowing users to supply the existing configuration format when starting providers from a file in the washboard

**Review by connorsmith256 — APPROVED** [review]
Sorry for the delay @rovast , and thank you for the contribution!

**Pull request merged**
