### PR TITLE
update wasmbus-rpc and capability providers

### PR DESCRIPTION
**Pull request by stevelr**
Signed-off-by: stevelr <steve@cosmonic.com>

### CODE REVIEW

**Comment by stevelr** [comment]
this PR includes capability provider sources and replaces cap provider binaries. I didn't change any actors - they are stuck in an examples PR

**Review by thomastaylor312 — APPROVED** [review]

**Review by autodidaddict — APPROVED** [review]

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
I see the echo unpriv test failed because it was allowed to make that invocation. I believe you mentioned this in slack, the echo unpriv actor needs to not have the `wasmcloud:httpserver` capability

**Comment by stevelr** [comment]
@brooksmtownsend I did remove the claim and left a comment in the Makefile:
https://github.com/wasmCloud/wasmcloud-otp/blob/eefc8877aaf1884d4495d86d8ab1efbce2236524/host_core/test/fixtures/actors/echo_unpriv/Makefile#L6

The test "fails" though, but Kevin said a failure is expected .. Is there a problem with the logic that is detecting the failure?

**Comment by brooksmtownsend** [comment]
@stevelr did you also recompile the webassembly module? from the test action:
```
  1) test unprivileged actor cannot receive undeclared invocations (HostCore.E2E.EchoTest)
Error:      test/e2e/echo_test.exs:78
     Assertion with == failed
     code:  assert resp.body == ""
     left:  "{\"body\":[],\"method\":\"GET\",\"path\":\"/foobar\",\"query_string\":\"\"}"
     right: ""
     stacktrace:
       test/e2e/echo_test.exs:126: (test)
```
it's supposed to assert that we get an empty string back and not a valid echo body

**Comment by brooksmtownsend** [comment]
@stevelr gave it a shot
```
on update/wasmcloud-rpc
~/github.com/wasmcloud/wasmcloud-otp/host_core/test/fixtures/actors ➜ wash claims inspect echo_unpriv_s.wasm

                           echo_unpriv - Module
  Account       ADYDCRUIFKCUZFVHZFBVZCPBR6HAT2U63VSVD2BBIWGM62KMJL5RR5YM
  Module        MCRACEYKJLCP7NLVMUTO2SCQ26JFL3Z4TBIXPXDE7KPBI2GEH5DA57L5
  Expires                                                          never
  Can Be Used                                                immediately
  Version                                                      0.4.0 (4)
  Call Alias                                                   (Not set)
                               Capabilities
  HTTP Server
                                   Tags
  None

```

You'll just have to recompile and replace the echo_unpriv actor

**Comment by stevelr** [comment]
will do - thanks!

**Pull request closed without merging**
