### PR TITLE
Fixed adding provider from file bug

### PR DESCRIPTION
**Pull request by aish-where-ya**
## Feature or Problem
Bug: Provider could not be added using a file reference like `file:\\provider-file.par.gz`
This bug has been fixed. 

## Related Issues
#639 
https://github.com/wasmCloud/wash/issues/540

## Release Information
Next

## Consumer Impact
Bug fix enabling starting a provider from file.

## Testing
Manually tested

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)
NA

### Acceptance or Integration
NA

### Manual Verification
Manually verified

### CODE REVIEW

**Review by connorsmith256 — APPROVED** [review]
🚀

**Comment by connorsmith256** [comment]
@aish-where-ya I'm not sure why dialyzer is failing; I suspect the cache is poisoned for some reason. Would you mind opening these changes in a new PR so we can see if that clears things up?

**Comment by brooksmtownsend** [comment]
> @aish-where-ya I'm not sure why dialyzer is failing; I suspect the cache is poisoned for some reason. Would you mind opening these changes in a new PR so we can see if that clears things up?

If cache is poisoned we may want to try clearing that out... let's see if we can delete these caches and re-run

**Comment by connorsmith256** [comment]
Ah, found some caches in GHA and cleared them out. 🤞

**Review by brooksmtownsend — APPROVED** [review]

**Pull request merged**
