### PR TITLE
build(native): switch to `wasmcloud-otp`

### PR DESCRIPTION
**Pull request by rvolosatovs**
## Related Issues

closes #640 

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### CODE REVIEW

**Review by autodidaddict — APPROVED** [review]
I'd made similar changes to my own PR, but I didn't think about the nix flake. Good catch

**Comment by autodidaddict** [comment]
LGTM so long as the build passes

**Comment by rvolosatovs** [comment]
> I'd made similar changes to my own PR, but I didn't think about the nix flake. Good catch

The CI in this repo was broken for a while apparently, as I mentioned earlier (at least for now) updates to `mix` dependencies require updating the hash in the flake

**Review by brooksmtownsend — DISMISSED** [review]

**Comment by autodidaddict** [comment]
Can this get fixed?
```
thread 'main' panicked at 'The NIF version given from RUSTLER_NIF_VERSION is not supported: 2.17', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustler_sys-2.2.0/build.rs:925:
```

**Comment by rvolosatovs** [comment]
> Can this get fixed?
> 
> ```
> thread 'main' panicked at 'The NIF version given from RUSTLER_NIF_VERSION is not supported: 2.17', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustler_sys-2.2.0/build.rs:925:
> ```

See https://github.com/rusterlium/rustler/issues/544

The issue is that OTP version used by CI is non-deterministic. Note, how it works just fine within Nix sandbox (because OTP version is locked)

**Comment by connorsmith256** [comment]
I don't follow. @rvolosatovs are you saying you expect CI to fail with this change? Do we need to/can we upgrade rustler to fix it?

**Comment by autodidaddict** [comment]
So I am still a bit fuzzy... @rvolosatovs is this something that you're comfortable merging, and saying that the 2 failing items (so far) are things we can safely ignore?

**Comment by rvolosatovs** [comment]
> So I am still a bit fuzzy... @rvolosatovs is this something that you're comfortable merging, and saying that the 2 failing items (so far) are things we can safely ignore?

I do not see any failures, CI is still running

**Comment by autodidaddict** [comment]
> > So I am still a bit fuzzy... @rvolosatovs is this something that you're comfortable merging, and saying that the 2 failing items (so far) are things we can safely ignore?
> 
> I do not see any failures, CI is still running

Yay for eventually consistent GUI. Github was showing me 2 failed runs but when I refreshed the status changed to "expected"

**Review by brooksmtownsend — APPROVED** [review]

**Review by autodidaddict — APPROVED** [review]

**Pull request merged**
