### PR TITLE
Add the cluster issuers list to the host data structure

### PR DESCRIPTION
**Pull request by autodidaddict**
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>

### CODE REVIEW

**Comment by autodidaddict** [comment]
Issuers list field will be a list of strings (public keys). list should never be empty because the host always tries to at least use the public key of its own signing key in the issuer list.

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
Will this cause issues with providers trying to deserialize the data structure and not knowing what to do with the `cluster_issuers` field? If so, we may want to hold off on this until we release `0.50.0` to avoid publishing all new versions of capability providers with minor version bumps

**Comment by autodidaddict** [comment]
I've watched the logs and none of the providers have an issue with the extraneous field.

**Comment by autodidaddict** [comment]
The tests all pass so we know they're able to get data from the host data struct

**Review by brooksmtownsend — APPROVED** [review]

**Comment by brooksmtownsend** [comment]
Touché, I forgot that integration tests, ya know, test integration.

**Comment by stevelr** [comment]
Serde deserialization ignores fields in the data stream that are not declared in the struct being deserialized into

**Comment by stevelr** [comment]
Changing the providers to parse and use the cluster keys will be in 0.51

**Pull request merged**
